modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"
issueTrackerURL="https://github.com/seymourimadeit/Piglin-Proliferation" #optional
# Access transformer definition
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
# Mixin config definition
[[mixins]]
config="${mod_id}.mixins.json"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${mod_version}" #mandatory
 # A display name for the mod
displayName="${mod_name}" #mandatory
authors="${mod_authors}"
updateJSONURL="https://api.modrinth.com/updates/piglin-proliferation/forge_updates.json" #optional
logoFile="piglinproliferation.png"
credits="Vivi for Buckler art, flowerfugue's friends Leo and Paula for translation help" #optional
description='''
Piglins expanded in new ways!
'''
[['dependencies.${mod_id}']]
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[['dependencies.${mod_id}']]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[modproperties.${mod_id}]
    catalogueItemIcon="piglinproliferation:piglin_alchemist_head"