name: Modrinth

on: [ workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          gradle-version: 8.4

      - name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: iRE67WIn
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files-primary: build/libs/!(*-@(javadoc|sources)).jar
          version-type: release
          version: 1.20.1-1.2.6
          loaders: |
            neoforge
            forge
          game-versions: 1.20.1
          java: 17
          name: ""
          changelog-file: changelog-1.20.1.*